ALTER TABLE productos
    ADD COLUMN created_at timestamp NOT NULL DEFAULT NOW();
ALTER TABLE productos
    ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE productos
    ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL;